controller_list:
  - name: /brc_arm/controller/trajectory
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - carriageJ
      - midarm1J
      - midarm2J
      - wrist1J
      - wrist2J
      - EEbaseJ