# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - brc_arm_controller
    - brc_arm_ee_controller

  brc_arm_controller:
    type: FollowJointTrajectory
    joints:
      - carriage_joint
      - midarm1_joint
      - midarm2_joint
      - wrist1_joint
      - wrist2_joint
    action_ns: follow_joint_trajectory
  brc_arm_ee_controller:
    type: FollowJointTrajectory
    joints:
      - EEbase_joint
      - Rlink_joint
    action_ns: follow_joint_trajectory