# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    brc_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    brc_arm_ee_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

brc_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - carriage_joint
      - midarm1_joint
      - midarm2_joint
      - wrist1_joint
      - wrist2_joint
brc_arm_ee_controller:
  ros__parameters:
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - EEbase_joint
      - Rlink_joint
